CREATE TABLE settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT,
    setting_group VARCHAR(50) DEFAULT 'general',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Insérer les valeurs par défaut lors de l'installation
INSERT INTO settings (setting_key, setting_value, setting_group) VALUES
('site_name', 'EstimIA', 'general'),
('site_phone', '', 'general'),
('site_email', '', 'general'),
('site_url', '', 'general'),
('target_city', '', 'general'),
('target_radius_km', '30', 'general'),
('site_color', '#2563eb', 'appearance'),
('site_logo_url', '', 'appearance'),
('hero_tagline', '', 'appearance'),
('company_name', '', 'company'),
('company_address', '', 'company'),
('company_siret', '', 'company'),
('company_rcs', '', 'company'),
('company_vat', '', 'company'),
('estimation_coef_neuf', '1.15', 'estimation'),
('estimation_coef_renove', '1.05', 'estimation'),
('estimation_coef_bon', '1.00', 'estimation'),
('estimation_coef_travaux', '0.85', 'estimation'),
('estimation_coef_refaire', '0.70', 'estimation'),
('estimation_coef_terrasse', '1.05', 'estimation'),
('estimation_coef_parking', '1.03', 'estimation'),
('estimation_coef_piscine', '1.07', 'estimation'),
('estimation_coef_vue', '1.04', 'estimation'),
('smtp_host', '', 'emails'),
('smtp_port', '587', 'emails'),
('smtp_user', '', 'emails'),
('smtp_password', '', 'emails'),
('smtp_encryption', 'tls', 'emails'),
('relance_j3_active', '1', 'emails'),
('relance_j7_active', '1', 'emails'),
('relance_j14_active', '0', 'emails'),
('notification_new_lead', '1', 'notifications'),
('notification_rdv', '1', 'notifications'),
('notification_high_score', '1', 'notifications'),
('notification_daily_summary', '0', 'notifications'),
('notification_email', '', 'notifications'),
('webhook_url', '', 'integrations'),
('calendly_url', '', 'integrations'),
('whatsapp_number', '', 'integrations'),
('google_analytics_id', '', 'integrations'),
('google_ads_id', '', 'integrations'),
('google_maps_api_key', '', 'integrations');
